spring.application.name=library

spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=sam17
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# File Upload
file.upload.photos=uploads/photos/
file.upload.payments=uploads/payments/

# CORS
app.cors.allowed-origins=http://localhost:5173

# Subscription
app.admin.phone=+91-7796849206
app.admin.upi-id=shamunmomin17-1@okaxis

# Multipart / File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Scheduling
spring.task.scheduling.enabled=true
